apiVersion: v1
kind: Pod
metadata:
  name: multipod
spec: 
  containers:
    - name: alpha
      image: nginx
      ports:
      - containerPort: 80
    - name: beta
      image: busybox
      command:
          - sleep
          - "4800"