apiVersion: v1
kind: Pod
metadata:
  name: redis-storage-ori
spec:
  containers:
  - name: redis-storage-ori
    image: redis:alpine
  volumes:
    - name: cache-volume
      emptyDir: {}
  volumeMounts:
   mountPath: /data/redis